language: node_js
repo_token: fI4YqX0TEKvE3BNMklEfaxQwVeQg0kXJ3

node_js:
  - "node"
cache:
  directories:
    - "node_modules"


before_script:
  - npm install
script:
  - npm run test
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info
